### ISSUE TITLE
Use config.yml file for text

### ISSUE THREAD

**Issue by arnfinn** [SKDE-Analyse/dynamiskTabellverk#60]
For `lagHjelpetekst` function. Something like:
```yml
heading: '<h1>Pasientstrømmer, Helse Nord RHF<img src=\"skde.png\" align=\"right\" width=\"150\" style=\"padding-right:20px;\"/></h1><br/>'
and: "og"
...
```
